### ISSUE TITLE
URL of new repo in README is incorrect

### ISSUE THREAD

**Issue by kristianperkins** [joeyh/myrepos#1]
The README states that the new repo is homed at https://git.joeyh.name/git/myrepos.git/ but that results in a 404.  Looks like the URL for the new repo should be: [https://git.joeyh.name/git/mr.git/](https://git.joeyh.name/git/mr.git/)

**Comment by joeyh** [comment]
Please submit changes to http://myrepos.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. Just open a todo item there and link to a git repository containing your changes. Did you know, git is a distributed system? The git repository doesn't even need to be on github! Please send any complaints to Github; they don't allow turning off pull requests or redirecting them elsewhere.  -- A robot acting on behalf of Joey Hess
